### PR TITLE
Cleanup and fixes for conditionals

### LINKED ISSUE #76: examples / reference about conditional relationships towards field values
i found [https://stackoverflow.com/a/38781027/2602592]( https://stackoverflow.com/a/38781027/2602592) extremely helpful as a reference for understanding the different approaches to schemas depending on field values. 

it covers dependencies, anyOf (Implication) and if-then-else

Would be a wonderful addition, though in the answer spans till v7.

### PR DESCRIPTION
**Pull request by jdesrosiers**
The content on this page was fine because I recently fixed the issues there. I moved `dependencies` from object to conditionals because it's a special case of a conditional. I also added a section on the Implication Pattern to help out people working with older drafts.

Fixes #76

### CODE REVIEW

**Comment by jdesrosiers** [comment]
The deploy preview for the page that change is here, https://deploy-preview-159--lucid-bardeen-10edfb.netlify.app/reference/conditionals.html

**Review by Relequestual — CHANGES_REQUESTED** [review]
The content looks good but I'm by default against using foobar in examples. It has been shown "real" examples are easier to understand.

Otherwise, good to merge.

**Comment by jdesrosiers** [comment]
@Relequestual I managed to come up with an example that I don't think it too distracting. Let me know what you think.

**Review by Relequestual — APPROVED** [review]
Thanks for sticking with me and finding an example

**Comment by Relequestual** [comment]
I still find it hard to internalise the implication pattern. I know it's logically sound but I still don't like it 😅

**Pull request merged**
