### PR TITLE
Add a Dockerfile to build an image to generate the docs

### PR DESCRIPTION
**Pull request by ghunti**
I've added a simple Dockerfile to build the docs.
Also updated the README with instructions on how you can use the Dockerfile to generate the docs

### CODE REVIEW

**Comment by embray** [comment]
This looks okay to me, though according to [the docs on Dockerhub](https://hub.docker.com/_/python/) it suggests running pip with `--no-cache-dir`, which makes sense.

I wonder if it would also make sense to add the correct `sphinx-build` command for building the docs in the Dockerfile's `CMD` instruction.  Perhaps also set the working directory by default to something like `/doc`, so that it's not necessary to pass the `-w` option to `docker run`.  That would simplify the invocation (and the usage instructions) to just something like `docker run -ti --rm -v $(pwd):/doc <image name>`

**Comment by ghunti** [comment]
@embray Real nice suggestions.
Sorry for taking long time ;)

**Comment by embray** [comment]
It looks good to me, thanks.  Let's see if @mdboom wants to add this.  Out of curiosity, what was your motivation?

**Comment by mdboom** [comment]
I'm happy to add this -- I think it will generally make it easier for others to contribute.

However, I'm a bit wary of it getting out-of-date if it's not being tested.

I'd like to move off of Travis-CI for other reasons anyway, so what if we used this as a basis for testing on Circle-CI.  Then we'd both be testing this docker image and using a better CI infrastructure...

**Comment by ghunti** [comment]
@embray I was trying to create a PR to the docs, but wanted to test the changes locally.
I ended up not making the PR and to be honest I don't remember now what was it about.
What do you have in mind @mdboom I've never used Travis before :-p

**Comment by ghunti** [comment]
@mdboom any news?

**Comment by Relequestual** [comment]
@mdboom What's the reason behind having a CI here? Is it purley to be able to see it builds without errors? I don't think there are any tests exactly.

If that's the case, we should migrate to netlify. It gives full site previews on every PR.

**Comment by mdboom** [comment]
There are basically doctests that run as part of the documentation build to make sure that the examples all validate or don't validate as expected.  CI is also used for automatic deployment of master.

I'd be quite happy to move this to netlify and get previewable PRs -- not sure I'll have bandwidth for that in the near future, though.

**Comment by Relequestual** [comment]
Noted. I'll aim to make a new issue for this. Will post here when the issue is created.

**Comment by jdesrosiers** [comment]
Closing in favor of #157

**Pull request closed without merging**
