### PR TITLE
Deploy with GitHub actions

### LINKED ISSUE #163: Migrate from Travis CI to GitHub Actions for build process
Our builds and deploys have stopped working because Travis CI .org is no longer working.
We could migrate to the new .com version, but might as well use GitHub Actions.

### PR DESCRIPTION
**Pull request by jdesrosiers**
Fixes #163 

This turned out to be pretty easy because Github Actions supports `docker-compose` out of the box. I was able to use the same docker setup for deployment as we do for local development. I used two third-party plugins. One to cache docker layers to make the build much faster and the other to deploy to Github Pages.

### CODE REVIEW

**Comment by derberg** [comment]
@jdesrosiers I think you are just missing the notification part that was handled by travis.

you have this one for email -> https://github.com/dawidd6/action-send-mail

if you prefer Slack notification or something then look at our workflow here -> https://github.com/asyncapi/.github/blob/master/.github/workflows/issues-prs-notifications.yml

**Comment by jdesrosiers** [comment]
@derberg Thanks for pointing that out, but I don't think we need notifications. I found in my testing that if the Github Action fails, it sends an email. I think that's sufficient. If anyone thinks we need more than that, I can look into it.

**Comment by gregsdennis** [comment]
> I found in my testing that if the Github Action fails, it sends an email.

The real trick is getting it to _not_ send an email on failures (which I haven't yet figured out how to do).  I'm usually watching my builds, so I don't need notification. And I have a lot of parallel actions doing different things; I don't need an email for each one that fails.

**Comment by Relequestual** [comment]
Any idea why the deploy preview doesn't include the PDF?

Thanks for looking into this Jason!

**Comment by derberg** [comment]
I recommend adding 👇🏼 `Deploy notifications` in Netlify (under `settings/deploys#deploy-notifications`) 
Screenshot 2021-06-25 at 13 08 59

as a result, you'll get such a lovely comment that points to preview, much more accessible than assuming the link is somewhere in the checks

Screenshot 2021-06-25 at 13 10 11

**Comment by Relequestual** [comment]
> I recommend adding 👇🏼 `Deploy notifications` in Netlify (under `settings/deploys#deploy-notifications`)

I thought it was something they stopped doing. Never looked into it again.

**Comment by Relequestual** [comment]
It's actually already enabled. Weird. I'll contact Netlify support

**Comment by jdesrosiers** [comment]
> Any idea why the deploy preview doesn't include the PDF?

I don't know how the Netlify build works, but I know that getting all the LaTeX dependencies installed was what was needed to get the PDF to build (and to fix other build issues) when I setup builds with docker.

**Comment by Relequestual** [comment]
> > Any idea why the deploy preview doesn't include the PDF?
> 
> I don't know how the Netlify build works, but I know that getting all the LaTeX dependencies installed was what was needed to get the PDF to build (and to fix other build issues) when I setup builds with docker.

It looks like I manually set the build command and resulting build location in the Netlify UI.

It can be set using a config file, but that shouldn't block this PR.

I'll make a new issue (https://docs.netlify.com/configure-builds/file-based-configuration/)

**Comment by Relequestual** [comment]
It doesn't look like it's picking up the new build command in this preview build. I think it's still fine to merge though. The deploy after merge should be fine.

**Pull request merged**
